require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RetrosController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Retro. As you add validations to Retro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RetrosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  context 'login is not required' do
    describe "GET index" do
      it "assigns all retros as @retros" do
        retro = Retro.create! valid_attributes
        get :index, {}, valid_session
        expect(assigns(:retros)).to eq([retro])
      end
    end

    describe "GET show" do
      it "assigns the requested retro as @retro" do
        retro = Retro.create! valid_attributes
        get :show, {:id => retro.to_param}, valid_session
        expect(assigns(:retro)).to eq(retro)
      end
    end
  end

  context 'login is required' do

    before :all do
      skip('need to figure out auth')
    end

    describe "GET new" do
      it "assigns a new retro as @retro" do
        get :new, {}, valid_session
        expect(assigns(:retro)).to be_a_new(Retro)
      end
    end

    describe "GET edit" do
      it "assigns the requested retro as @retro" do
        retro = Retro.create! valid_attributes
        get :edit, {:id => retro.to_param}, valid_session
        expect(assigns(:retro)).to eq(retro)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new Retro" do
          expect {
            post :create, {:retro => valid_attributes}, valid_session
          }.to change(Retro, :count).by(1)
        end

        it "assigns a newly created retro as @retro" do
          post :create, {:retro => valid_attributes}, valid_session
          expect(assigns(:retro)).to be_a(Retro)
          expect(assigns(:retro)).to be_persisted
        end

        it "redirects to the created retro" do
          post :create, {:retro => valid_attributes}, valid_session
          expect(response).to redirect_to(Retro.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved retro as @retro" do
          post :create, {:retro => invalid_attributes}, valid_session
          expect(assigns(:retro)).to be_a_new(Retro)
        end

        it "re-renders the 'new' template" do
          post :create, {:retro => invalid_attributes}, valid_session
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          skip("Add a hash of attributes valid for your model")
        }

        it "updates the requested retro" do
          retro = Retro.create! valid_attributes
          put :update, {:id => retro.to_param, :retro => new_attributes}, valid_session
          retro.reload
          skip("Add assertions for updated state")
        end

        it "assigns the requested retro as @retro" do
          retro = Retro.create! valid_attributes
          put :update, {:id => retro.to_param, :retro => valid_attributes}, valid_session
          expect(assigns(:retro)).to eq(retro)
        end

        it "redirects to the retro" do
          retro = Retro.create! valid_attributes
          put :update, {:id => retro.to_param, :retro => valid_attributes}, valid_session
          expect(response).to redirect_to(retro)
        end
      end

      describe "with invalid params" do
        it "assigns the retro as @retro" do
          retro = Retro.create! valid_attributes
          put :update, {:id => retro.to_param, :retro => invalid_attributes}, valid_session
          expect(assigns(:retro)).to eq(retro)
        end

        it "re-renders the 'edit' template" do
          retro = Retro.create! valid_attributes
          put :update, {:id => retro.to_param, :retro => invalid_attributes}, valid_session
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested retro" do
        retro = Retro.create! valid_attributes
        expect {
          delete :destroy, {:id => retro.to_param}, valid_session
        }.to change(Retro, :count).by(-1)
      end

      it "redirects to the retros list" do
        retro = Retro.create! valid_attributes
        delete :destroy, {:id => retro.to_param}, valid_session
        expect(response).to redirect_to(retros_url)
      end
    end
  end
end
