require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RetrosController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Retro. As you add validations to Retro, be sure to
  # adjust the attributes here as well.
  let(:invalid_attributes) {
    { :pizza => "pepperoni" }
  }

  let(:valid_session) { { 'user_id' => 1 } }

  let(:valid_attributes) {
    { :project_id => 1,
      :creator_id => 1,
      :meeting_date => DateTime.new.to_s,
      :status => 'New'
    }
  }

  # This should return the minimal set of attributes required to create a valid
  # Issues. As you add validations to Issues, be sure to
  # adjust the attributes here as well.
  before :each do
    @project = FactoryGirl.create(:project)
    @project.save
    @user = FactoryGirl.create(:user)
    @user.save
  end

  context 'login is not required' do
    describe "GET index" do
      it "assigns all retros as @retros" do
        retro = Retro.create! valid_attributes
        get :index, { :project_id => 1 }, valid_session
        expect(assigns(:retros)).to eq([retro])
      end
    end

    describe "GET show" do
      it "assigns the requested retro as @retro" do
        retro = Retro.create! valid_attributes
        get :show, {:project_id => 1, :id => retro.to_param}, valid_session
        expect(assigns(:retro)).to eq(retro)
      end
    end
  end

  context 'login is required' do
    describe "GET new" do
      it "assigns a new retro as @retro" do
        get :new, {:project_id => 1}, valid_session
        expect(assigns(:retro)).to be_a_new(Retro)
      end
    end

    describe "GET edit" do
      it "assigns the requested retro as @retro" do
        retro = Retro.create! valid_attributes
        get :edit, {:project_id => 1, :id => retro.to_param}, valid_session
        expect(assigns(:retro)).to eq(retro)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new Retro" do
          expect {
            post :create, {:project_id => 1, :retro => valid_attributes}, valid_session
          }.to change(Retro, :count).by(1)
        end

        it "assigns a newly created retro as @retro" do
          post :create, {:project_id => 1, :retro => valid_attributes}, valid_session
          expect(assigns(:retro)).to be_a(Retro)
          expect(assigns(:retro)).to be_persisted
        end

        it "redirects to the created retro" do
          post :create, {:project_id => 1, :retro => valid_attributes}, valid_session
          expect(response).to redirect_to(Retro.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved retro as @retro" do
          post :create, {:project_id => 1, :retro => invalid_attributes}, valid_session
          expect(assigns(:retro)).to be_a_new(Retro)
        end

        it "re-renders the 'new' template" do
          post :create, {:project_id => 1, :retro => invalid_attributes}, valid_session
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          { :project_id => 1,
            :creator_id => 1,
            :meeting_date => DateTime.new.to_s,
            :status => 'Finished'
          }
        }

        it "updates the requested retro" do
          retro = Retro.create! valid_attributes
          put :update, {:project_id => 1, :id => retro.to_param, :retro => new_attributes}, valid_session
          retro.reload
          new_attributes.each { |key,value|
            expect(retro[key]).to eq(value)
          }
        end

        it "assigns the requested retro as @retro" do
          retro = Retro.create! valid_attributes
          put :update, {:project_id => 1, :id => retro.to_param, :retro => valid_attributes}, valid_session
          expect(assigns(:retro)).to eq(retro)
        end

        it "redirects to the retro" do
          retro = Retro.create! valid_attributes
          put :update, {:project_id => 1, :id => retro.to_param, :retro => valid_attributes}, valid_session
          expect(response).to redirect_to(retro)
        end
      end

      describe "with invalid params" do
        it "assigns the retro as @retro" do
          retro = Retro.create! valid_attributes
          put :update, {:project_id => 1, :id => retro.to_param, :retro => invalid_attributes}, valid_session
          expect(assigns(:retro)).to eq(retro)
        end

        it "re-renders the 'edit' template" do
          retro = Retro.create! valid_attributes
          put :update, {:project_id => 1, :id => retro.to_param, :retro => invalid_attributes}, valid_session
          expect(response).to redirect_to(retro_url)
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested retro" do
        retro = Retro.create! valid_attributes
        expect {
          delete :destroy, {:project_id => 1, :id => retro.to_param}, valid_session
        }.to change(Retro, :count).by(-1)
      end

      it "redirects to the retros list" do
        retro = Retro.create! valid_attributes
        delete :destroy, {:project_id => 1, :id => retro.to_param}, valid_session
        expect(response).to redirect_to(project_retros_url({:project_id => 1}))
      end
    end
  end
end
